# Generated by Django 5.0.4 on 2024-04-14 02:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_tour_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(2, 'Tour name must be at least 2 characters long'), django.core.validators.MaxLengthValidator(100, 'Tour name must be at most 100 characters long')]),
        ),
    ]
