version: "3.9"

services:
    db:
        image: postgres
        environment:
            POSTGRES_DB: test_database
            POSTGRES_USER: test_user
            POSTGRES_PASSWORD: test_password
        ports:
            - "5432:5432"
