version: '3.9'

services:
    postgres:
        image: postgres:16-alpine
        ports:
            - '5432:5432'
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=touringdb

volumes:
    postgres-data:
